Wasm release
y-crdt/ypy pull request #99
Opened 2022-11-29 23:52 UTC by kafonek

Closes https://github.com/y-crdt/ypy/issues/96

The way this should work is that when we create a release via the Github UI (Releases -> draft new release -> create new tag like `v0.5.6`), that will trigger CI and build wheels / upload to Pypi like normal. In addition, it will build the `emscripten` / wasm wheel and upload that as an asset to the Release. 

 - `emscripten` / WASM wheels will be built and the artifacts uploaded to a separate CI namespace than the other wheels (`wasm_wheel` vs `wheels`)
 - A new job in CI that only runs on tagged releases will pull in the wasm wheel binaries and upload them as assets to the release with the same name as the git tag
 - Had to remove the dependencies in pyproject.toml in order to import the wasm wheel in pyodide (`maturin` has no pure Python wheel, since it is also a Rust-based Python library)
 - Tweaked the tests to not use hatch since it's handling the matrix in CI, and our docs already tell people to pip install pytest/maturin to build/test one-offs. Added a separate section in the docs for using hatch to build/test locally against a matrix
 - Added a section in docs for demo'ing Ypy in Pyodide

2022-12-08 19:47 UTC, Waidhoferj requested changes
Hey @kafonek, thanks for the fix! Looks good overall, just a small spelling update in the README

2022-12-10 05:36 UTC, Waidhoferj approved these changes
Looks good!

2022-12-10 06:33 UTC, kafonek commented
(Merge at your leisure @Waidhoferj, I don't have permissions to do so)

2022-12-13 16:04 UTC, merged

2022-12-13 16:58 UTC, kafonek commented
😐 Well, thought I had adequately tested this. This is frustrating to say the least. Works on my fork!

![image](https://user-images.githubusercontent.com/3867768/207395937-37211b50-2740-4061-bd26-028f9fad97d2.png)

![image](https://user-images.githubusercontent.com/3867768/207396036-dae09ece-2de1-4c31-a1e3-c9db8a5a36b2.png)

2022-12-13 17:32 UTC, kafonek commented
@Waidhoferj biggest difference I see between the action run in my fork / PR source and the post-merge action is that my `ubuntu-latest` came out as 20.04 while the `y-crdt/ypy` run `ubuntu-latest` resolved to 22.04.

https://github.com/actions/runner-images/issues/6399 maybe related?